version: "3"
services:
  conduit:
    build: .
    environment:
      - ASPNETCORE_Conduit_DatabaseProvider=${ASPNETCORE_Conduit_DatabaseProvider}
      - ASPNETCORE_Conduit_ConnectionString=${ASPNETCORE_Conduit_ConnectionString}
    ports:
      - "5002:5000"
